name: wf-cd-development
on: 
  push:
   branches:
     - develop
jobs:
 cd-build-development-job:
   runs-on: ubuntu-latest
   steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Created Build artifacts
      run: |
        npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
     - name: Upload Development Artifacts
       uses: actions/upload-pages-artifact@v3
       with:
         path: "./dist"
         name: "developemnt-artifact"

 cd-deploy-development-job:
    needs: "cd-build-development-job"
    envirnment: "development-env"
    permissions:
     pages: write
     id-token: write
    runs-on : ubuntu-latest
    steps:
     - name: Deploy Artifacts
       uses: actions/deploy-pages@v4
       with: 
         artifact-name: "developemnt-artifact"
         token: ${{github.token}}


     