name: wf-ci-development
on:
   pull request:
    branhces:
    - develop
jobs:
  ci-development-job:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Repo
     uses: actions/checkout@v4
   - name: Lint HTML and CSS Code
     run: |
       npx htmlhint "**/*.html"
       npx stylelint "**/*.css"
   - name: Test Build
     run: |
       npx parcel build "./src/index.html" --dist-dit "./dist" --publuc-url "./"
       
      